server:
  port: 8888

spring:
  application:
    name: config

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Cos125RUS/Manager.Config
          default-label: main
          search-paths: "{application}"