server:
  port: 8888

spring:
  application:
    name: config

  cloud:
    config:
      server:
#        git:
#          uri: https://github.com/Evgen986/shop-config.git
#          basedir: file://c:/tmp/shop
#          default-label: main
