server:
  port:
    8765

spring:
  application:
    name:
      gateway

  cloud:
    gateway:
      routes:
#        - id: auth
#          uri: http://localhost:/
#          predicates:
#            - Path=/auth/**