server:
  port:
    8765

spring:
  application:
    name:
      gateway

  cloud:
    gateway:
      routes:
        - id: clients
          uri: http://localhost:8081/
          predicates:
            - Path=/clients/**
        - id: catalog
          uri: http://localhost:8082/
          predicates:
            - Path=/catalog/**
        - id: storage
          uri: http://localhost:8083/
          predicates:
            - Path=/storage/**
#        - id: auth
#          uri: http://localhost:/
#          predicates:
#            - Path=/auth/**

#  config:
#    import: configserver:http://localhost:8888