server:
  port:
    8765

spring:
  application:
    name:
      gateway

  cloud:
    gateway:
      routes:
        - id: clients
          url: http://localhost:8081/
          predicates:
            - Path=/clients/**
#        - id: auth
#          uri: http://localhost:/
#          predicates:
#            - Path=/auth/**