server:
  port:
    8082

spring:
  application:
    name:
      storage

  datasource:
    url: jdbc:postgresql://localhost:65432/storage_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  metrics:
#    export:
#      prometheus:
#        enable: true

