server:
  port:
    8083

spring:
  application:
    name:
      storage
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      fail-fast: true


#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  metrics:
#    export:
#      prometheus:
#        enable: true

